import type { SherlockArtifactEnvelope } from "@/lib/sherlock/types"

export const mockSherlockArtifact: SherlockArtifactEnvelope = {
  artifactType: "sherlock_evidence_report",
  version: "1.0",
  sessionId: "mock-session-alex-rivera",
  generatedAt: "2026-06-17T02:30:00.000Z",
  candidate: {
    displayName: "Alex Rivera",
    handles: [
      {
        source: "GitHub",
        value: "alexrivera",
        url: "https://github.com/alexrivera",
        confidence: "high",
      },
      {
        source: "Portfolio",
        value: "alexrivera.dev",
        url: "https://alexrivera.dev",
        confidence: "medium",
      },
    ],
  },
  targetRole: "Senior Rust Engineer",
  summary: {
    verified: 2,
    contradicted: 1,
    unverified: 2,
    needsAlternativeProof: 1,
    humanReviewRequired: true,
  },
  githubDepth: {
    username: "alexrivera",
    ownedRepos: 9,
    forkedRepos: 4,
    authoredCommits: 312,
    cadenceSummary: "Public activity shows steady authorship across owned backend repositories from 2024 to 2026.",
    languageSignals: [
      {
        language: "TypeScript",
        basis: "authored_commits",
        summary: "Repeated authored commits in service and dashboard repositories.",
      },
      {
        language: "Python",
        basis: "authored_commits",
        summary: "Evidence appears in data ingestion and automation scripts.",
      },
      {
        language: "Rust",
        basis: "repo_level_context",
        summary: "One Rust repository appears in public profile; authored depth still needs deeper verification.",
      },
    ],
    noiseSignals: [
      "Four forked repositories are separated from owned work.",
      "One tutorial-style repository is treated as weak evidence only.",
      "Repo-level language data is labeled as context, not proof.",
    ],
  },
  claims: [
    {
      id: "claim-stack-rust",
      type: "stack",
      text: "Candidate claims senior Rust backend experience.",
      subject: "Rust backend",
      source: "Resume",
      sourceSnippet: "Senior Rust Engineer with distributed systems experience.",
    },
    {
      id: "claim-stack-typescript",
      type: "stack",
      text: "Candidate claims production TypeScript and API work.",
      subject: "TypeScript APIs",
      source: "Resume",
      sourceSnippet: "Built TypeScript APIs and internal dashboards.",
    },
    {
      id: "claim-tenure",
      type: "tenure",
      text: "Candidate claims backend engineering work from 2023 to 2026.",
      subject: "Backend tenure",
      source: "LinkedIn paste",
      sourceSnippet: "Backend Engineer, 2023-present.",
    },
    {
      id: "claim-scope",
      type: "scope",
      text: "Candidate claims ownership of payments architecture.",
      subject: "Payments architecture",
      source: "Resume",
      sourceSnippet: "Owned payments architecture for a high-volume product.",
    },
    {
      id: "claim-identity",
      type: "identity",
      text: "Resume and GitHub profile appear to refer to the same person.",
      subject: "Identity continuity",
      source: "Resume and GitHub",
      sourceSnippet: "Resume lists github.com/alexrivera and portfolio alexrivera.dev.",
    },
  ],
  evidence: [
    {
      id: "ev-github-owned-repos",
      sourceType: "primary_artifact",
      sourceName: "GitHub public API",
      sourceUrl: "https://github.com/alexrivera",
      retrievedAt: "2026-06-17T02:30:00.000Z",
      artifactDate: "2026-05-21",
      summary: "Owned repositories show regular TypeScript and Python backend activity.",
      details: ["9 owned repositories", "312 matched authored commits", "Forked repositories separated from primary evidence"],
      reliability: "primary_artifact",
    },
    {
      id: "ev-rust-repo-context",
      sourceType: "primary_artifact",
      sourceName: "GitHub repository language context",
      sourceUrl: "https://github.com/alexrivera/rust-queue-lab",
      retrievedAt: "2026-06-17T02:30:00.000Z",
      artifactDate: "2025-09-10",
      summary: "Rust appears in one lab repository, but current mock depth does not prove senior production Rust.",
      details: ["Small repository", "Limited commit history", "No production deployment artifact attached"],
      reliability: "primary_artifact",
    },
    {
      id: "ev-portfolio-api",
      sourceType: "primary_artifact",
      sourceName: "Portfolio",
      sourceUrl: "https://alexrivera.dev",
      retrievedAt: "2026-06-17T02:30:00.000Z",
      artifactDate: "2026-01-18",
      summary: "Portfolio links the same GitHub account and describes API projects.",
      details: ["Cross-links GitHub handle", "Mentions API and ingestion projects", "Does not independently verify payments scale"],
      reliability: "primary_artifact",
    },
    {
      id: "ev-resume",
      sourceType: "self_reported",
      sourceName: "Uploaded resume",
      retrievedAt: "2026-06-17T02:30:00.000Z",
      summary: "Resume provides claim set only and is not treated as verification.",
      details: ["Contains stack, tenure, and scope claims", "Used as zero-trust claim input"],
      reliability: "self_reported",
    },
  ],
  verifications: [
    {
      id: "ver-stack-rust",
      claimId: "claim-stack-rust",
      state: "contradicted",
      summary: "Current public evidence does not support senior Rust depth; the available Rust signal is limited to a small lab repository.",
      supportingEvidenceIds: [],
      contradictingEvidenceIds: ["ev-rust-repo-context"],
      proofRoute: "Ask for a Rust systems walkthrough or private work sample.",
      humanReviewRequired: true,
    },
    {
      id: "ver-stack-typescript",
      claimId: "claim-stack-typescript",
      state: "verified",
      summary: "Owned repositories and portfolio context support repeated TypeScript API work.",
      supportingEvidenceIds: ["ev-github-owned-repos", "ev-portfolio-api"],
      contradictingEvidenceIds: [],
      humanReviewRequired: true,
    },
    {
      id: "ver-tenure",
      claimId: "claim-tenure",
      state: "verified",
      summary: "Public activity brackets backend work across the claimed period.",
      supportingEvidenceIds: ["ev-github-owned-repos"],
      contradictingEvidenceIds: [],
      humanReviewRequired: true,
    },
    {
      id: "ver-scope",
      claimId: "claim-scope",
      state: "needs_alternative_proof",
      summary: "Payments architecture ownership is not publicly corroborated; private company work may exist.",
      supportingEvidenceIds: [],
      contradictingEvidenceIds: [],
      proofRoute: "Route to architecture interview, reference request, or sanitized design artifact.",
      humanReviewRequired: true,
    },
    {
      id: "ver-identity",
      claimId: "claim-identity",
      state: "unverified",
      summary: "Resume and portfolio cross-link the GitHub handle, but stronger identity continuity should use user-approved sources.",
      supportingEvidenceIds: ["ev-portfolio-api"],
      contradictingEvidenceIds: [],
      proofRoute: "Ask for candidate-confirmed profile links or approved LinkedIn export.",
      humanReviewRequired: true,
    },
  ],
  contradictionCards: [
    {
      id: "contradiction-rust-depth",
      title: "Rust seniority claim needs challenge",
      claimId: "claim-stack-rust",
      evidenceIds: ["ev-rust-repo-context"],
      summary: "The public Rust artifact is narrow and lab-like, while the claim says senior backend depth.",
      interviewPrompt: "Walk me through a Rust concurrency or ownership issue you debugged in production, including the tradeoffs you considered.",
    },
  ],
  interviewPack: [
    {
      id: "q-rust-depth",
      question: "Which Rust service best represents your production work, and what changed after the first incident or load test?",
      reason: "Targets the gap between senior Rust claim and limited public Rust evidence.",
      linkedClaimIds: ["claim-stack-rust"],
      linkedEvidenceIds: ["ev-rust-repo-context"],
    },
    {
      id: "q-payments-scope",
      question: "Please diagram the payments architecture you owned and mark which parts you personally designed, reviewed, or operated.",
      reason: "Routes an unverified scope claim to human evidence.",
      linkedClaimIds: ["claim-scope"],
      linkedEvidenceIds: [],
    },
    {
      id: "q-identity",
      question: "Can you confirm the public profiles and provide any approved export or reference that links them to you?",
      reason: "Improves identity continuity without relying on unauthorized scraping.",
      linkedClaimIds: ["claim-identity"],
      linkedEvidenceIds: ["ev-portfolio-api"],
    },
  ],
  proofRoutes: [
    {
      id: "route-private-rust",
      label: "Private repository walkthrough",
      reason: "Public evidence may not include private company code.",
      requestedArtifacts: ["Screenshared private repo walkthrough", "Sanitized pull request", "Reference from technical lead"],
    },
    {
      id: "route-payments",
      label: "Architecture proof path",
      reason: "Scope and impact are rarely fully public.",
      requestedArtifacts: ["System design walkthrough", "Incident review", "Architecture doc excerpt"],
    },
  ],
  timeline: [
    {
      id: "timeline-2023",
      date: "2023",
      label: "Claimed backend engineering start",
      source: "LinkedIn paste",
      state: "verified",
    },
    {
      id: "timeline-2024",
      date: "2024",
      label: "Public authored API work appears across owned repositories",
      source: "GitHub",
      state: "verified",
    },
    {
      id: "timeline-2025",
      date: "2025",
      label: "Small Rust lab repository appears",
      source: "GitHub",
      state: "contradicted",
    },
    {
      id: "timeline-2026",
      date: "2026",
      label: "Payments architecture scope remains uncorroborated",
      source: "Resume",
      state: "needs_alternative_proof",
    },
  ],
  auditRefs: ["audit-session-created", "audit-mock-claims-loaded", "audit-mock-report-generated"],
  prohibitedOutputsAbsent: {
    noScore: true,
    noRanking: true,
    noAutoReject: true,
  },
}
